# k8s/ingres-dev.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: blog
spec:
  ingressClassName: traefik
  rules:
    - host: blog.local # It may need to be added to the hosts file.
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-django
                port:
                  number: 8000
