# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: blog
  annotations:
    # the entry point used by the route (WebSecure corresponds to HTTPS port 443).
    traefik.ingress.kubernetes.io/router.entrypoint: websecure
    # enable TLS encryption
    traefik.ingress.kubernetes.io/router.tls: "true"
    # HTTP redirect to HTTPS
    traefik.ingress.kubernetes.io/router.middlewares: blog-blog-redirect-scheme@kubernetescrd
    # rate limiting
    traefik.ingress.kubernetes.io/ratelimit.average: "100"
    # certificate management
    # install cert-manager first, https://cert-manager.io/docs/installation/
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ${BACKEND_DOMAIN}
      secretName: blog-django-tls-secret
  rules:
    - host: ${BACKEND_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-django
                port:
                  number: 8000

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: blog-redirect-scheme
  namespace: blog
spec:
  redirectScheme:
    scheme: https
    permanent: true

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${ADMIN_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik
