# k8s/postgres.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-postgres-pvc
  namespace: blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path # k3s local storage

---

apiVersion: apps/v1
kind: StatefulSet # PostgreSQL is a stateful service
metadata:
  name: blog-postgres
  namespace: blog
spec:
  serviceName: blog-postgres
  replicas: 1 # deploy only 1 replica (single-node PostgreSQL)
  selector:
    matchLabels:
      app: blog-postgres
  template:
    metadata:
      labels:
        app: blog-postgres
    spec:
      volumes: # associate PVC with Pod
        - name: blog-postgres-storage
          persistentVolumeClaim:
            claimName: blog-postgres-pvc
      containers:
        - name: blog-postgres
          image: pgvector/pgvector:pg17-trixie
          ports:
            - containerPort: 5432
          volumeMounts: # mount the PVC
            - name: blog-postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m" # 1000m == 1 cpu core
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: DATABASE_PASSWORD
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: blog-postgres
  namespace: blog
spec:
  selector:
    app: blog-postgres
  ports:
    - port: 5432 # expose by service
      targetPort: 5432 # Pod's port
  type: ClusterIP # accessible only within the cluster
