# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blog
type: Opaque
stringData:
  # NOTE: kubectl does not automatically expand ${VAR} variables
  # Use envsubst or similar tools to replace variables before applying
  #
  # django
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
  DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS}
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  FRONTEND_URL: ${FRONTEND_URL}
  SERVER_NAME: ${SERVER_NAME}
  # redis
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  # database
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  # service
  API_KEY: ${API_KEY}
  HUGGINGFACE_HUB_TOKEN: ${HUGGINGFACE_HUB_TOKEN}
  # resend
  RESEND_API_KEY: ${RESEND_API_KEY}
  ADMIN_EMAIL: ${ADMIN_EMAIL}
  # S3 Storage
  S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
  S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
  S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
